### ISSUE TITLE
how to handle the userModel ?

### ISSUE THREAD

**Issue by skeeran** [akbarjoudi/yii2-vue#6]
Hi, 
can u explain me how to handle a Object that comes from Yii2 like
` 'userModel' => User::findOne(Yii::$app->user->id),`

because for me its empty

Thanks

**Comment by gogl92** [comment]
you can use:
Json Encode

`use yii\helpers\Json;`
`'personal' => Json::encode(User::find()->where(['id'=>Yii::$app->user->id])->one()),`

That will print the User object as a json string.

**Comment by akbarjoudi** [comment]
Thankful. Saw should be like that
